# docker-compose.dev.yml - Development overrides
# This file is used with docker-compose.yml using: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Database Service - Development overrides
  db:
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    command: postgres -c log_statement=all -c shared_buffers=256MB -c max_connections=200

  # Server Service - Development overrides
  server:
    build:
      target: development
    volumes:
      - ./server:/app:cached
      - server_go_mod_cache:/go/pkg/mod
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - APP_ENV=development
      - GIN_MODE=debug
      - LOG_LEVEL=debug

  # Client Service - Development overrides
  client:
    build:
      target: development
    volumes:
      # Mount source code but exclude node_modules and .next
      - ./client:/app:cached
      - client_node_modules:/app/node_modules
      - client_next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:${SERVER_PORT:-8080}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-true}
    # Ensure the .next directory has proper permissions before starting
    command: >
      sh -c "
        mkdir -p /app/.next &&
        npm run dev
      "

  # Nginx - Development overrides
  nginx:
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

# Additional volumes for development
volumes:
  server_go_mod_cache:
  client_node_modules:
  client_next_cache:
