# Simplified Air configuration for hot reloading in Go
# https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
# Build command
cmd = "go build -o ./tmp/main ."
# Binary file to run
bin = "tmp/main"
# Watch these filename extensions
include_ext = ["go", "mod", "sum"]
# Ignore these directories
exclude_dir = ["tmp", "vendor", ".git"]
# Delay between builds
delay = 1000 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
