package middleware

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

const requestIDContextKey = "requestID"

type requestLogEntry struct {
	Type            string  `json:"type"`
	Timestamp       string  `json:"timestamp"`
	RequestID       string  `json:"requestId"`
	Method          string  `json:"method"`
	Path            string  `json:"path"`
	Route           string  `json:"route"`
	Status          int     `json:"status"`
	DurationMS      float64 `json:"durationMs"`
	ResponseBytes   int     `json:"responseBytes"`
	ClientIP        string  `json:"clientIp,omitempty"`
	UserID          string  `json:"userId,omitempty"`
	ClientComponent string  `json:"clientComponent,omitempty"`
	ClientAction    string  `json:"clientAction,omitempty"`
}

// RequestObservability logs one structured event per request and propagates a request ID.
func RequestObservability() gin.HandlerFunc {
	return func(c *gin.Context) {
		startedAt := time.Now()

		requestID := strings.TrimSpace(c.GetHeader("X-Request-ID"))
		if requestID == "" {
			requestID = generateRequestID()
		}

		c.Set(requestIDContextKey, requestID)
		c.Writer.Header().Set("X-Request-ID", requestID)

		c.Next()

		route := c.FullPath()
		if route == "" {
			route = c.Request.URL.Path
		}

		entry := requestLogEntry{
			Type:            "http_request",
			Timestamp:       time.Now().UTC().Format(time.RFC3339Nano),
			RequestID:       requestID,
			Method:          c.Request.Method,
			Path:            c.Request.URL.Path,
			Route:           route,
			Status:          c.Writer.Status(),
			DurationMS:      float64(time.Since(startedAt).Microseconds()) / 1000.0,
			ResponseBytes:   c.Writer.Size(),
			ClientIP:        c.ClientIP(),
			ClientComponent: strings.TrimSpace(c.GetHeader("X-Client-Component")),
			ClientAction:    strings.TrimSpace(c.GetHeader("X-Client-Action")),
		}

		if userID, ok := c.Get("userID"); ok {
			if normalized := formatUserID(userID); normalized != "" {
				entry.UserID = normalized
			}
		}

		payload, err := json.Marshal(entry)
		if err != nil {
			log.Printf("{\"type\":\"http_request_log_error\",\"error\":%q}", err.Error())
			return
		}
		log.Println(string(payload))
	}
}

// GetRequestID returns the request ID generated by RequestObservability middleware.
func GetRequestID(c *gin.Context) string {
	if c == nil {
		return ""
	}
	value, exists := c.Get(requestIDContextKey)
	if !exists {
		return ""
	}
	requestID, ok := value.(string)
	if !ok {
		return ""
	}
	return strings.TrimSpace(requestID)
}

func generateRequestID() string {
	buf := make([]byte, 12)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("req_%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(buf)
}

func formatUserID(value interface{}) string {
	switch v := value.(type) {
	case uint:
		return strconv.FormatUint(uint64(v), 10)
	case uint8:
		return strconv.FormatUint(uint64(v), 10)
	case uint16:
		return strconv.FormatUint(uint64(v), 10)
	case uint32:
		return strconv.FormatUint(uint64(v), 10)
	case uint64:
		return strconv.FormatUint(v, 10)
	case int:
		return strconv.Itoa(v)
	case int8:
		return strconv.Itoa(int(v))
	case int16:
		return strconv.Itoa(int(v))
	case int32:
		return strconv.Itoa(int(v))
	case int64:
		return strconv.FormatInt(v, 10)
	case string:
		return strings.TrimSpace(v)
	default:
		return strings.TrimSpace(fmt.Sprintf("%v", v))
	}
}
